### ISSUE TITLE
Temporary layer

### ISSUE THREAD

**Issue by katagen** [mblesius/unique_values_viewer#2]
Hi,
Is it possible that the plugin also works on "temporary layer"?
For now, I have an error on such files!

Thank you

**Comment by malbles** [comment]
Hello,

_Temporary Vector Layers_ should be working in the current version of the plugin. Unfortunately, not all field types are supported. Can you further specify on which field type the error occurs?

**Comment by katagen** [comment]
It's on `string` type. If my layer is temporary, and I try to use the plugin, I have an error.
I first need to export it in a .gpkg, and then using the plugin is OK!

I didn't not try the plugin on other field types.

**Comment by freeshrugsxd** [comment]
@katagen Is this the error you're seeing?

```
AttributeError: 'NoneType' object has no attribute 'lower' 
Traceback (most recent call last):
  File "/home/silvio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/unique_values_viewer/unique_values_viewer_dockwidget.py", line 856, in update_values
    values = self.get_unique_values()
  File "/home/silvio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/unique_values_viewer/unique_values_viewer_dockwidget.py", line 648, in get_unique_values
    if self.fieldType.lower() in {'datetime', 'date'}:
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by katagen** [comment]
Exactly!

**Comment by freeshrugsxd** [comment]
They already fixed that in the git version but the change did not yet make it into the plugin repository. 

Usually you could download the git repo and put it into your plugins folder but the current main branch seems to be broken.

A quick workaround for the time being is to add a `self.change_field()` call to the `unique_values_viewer_dockwidget.py` at line `342`:

So that the lines 339 - 342 look like this:
```
                else:
                    field = self.mapLayer.fields()[0]
                    self.mFieldComboBox.setField(field.name())
                    self.change_field()
```

EDIT: The problem also goes away by clicking the Target Field dropdown menu. Even if you just choose the same field again. The problem is just that the self.fieldType property wasn't set properly when the plugin chooses the initial selected field. It is not specific to temporary layers or string field types
